# docker-compose up --build --force-recreate

version: "3.9"

services:

  modbus-server:
    container_name: modbus-server
    image: oitc/modbus-server
    restart: always
    command: -f /server_config.json
    ports:
      - 5020:5020
    volumes:
      - ./server.json:/server_config.json:ro
    networks:
      sensorfact:
        ipv4_address: 172.28.5.1

  exporter-ecoadapt:
    container_name: exporter-ecoadapt
    build: ./src
    restart: unless-stopped
    command: python ./exporter-ecoadapt/websocket_client.py -mh 172.28.5.1 -mp 5020 --server 172.28.5.3
    volumes:
      - ./src/:/usr/src/
    networks:
      sensorfact:
        ipv4_address: 172.28.5.2
    depends_on:
      - sensorfact-server
      - modbus-server

  sensorfact-server:
    container_name: sensorfact-server
    restart: unless-stopped
    build: ./dev
    ports:
      - 9000:9000
    command: python ./server.py --port 9000
    networks:
      sensorfact:
        ipv4_address: 172.28.5.3

networks:
  sensorfact:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
          gateway: 172.28.5.254